name: Build and upload to Maestro Cloud (Native Android)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest
    outputs:
      app: app/build/outputs/apk/debug
    jobs:
  test_access_token:
    runs-on: ...
    steps:
      - id: google-token
        uses: playeveryware/action-google-access-token@v1
        with:
          credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
          scope: 'https://www.googleapis.com/auth/drive.readonly'

      - name: Show (masked) token
        run: |
          echo "Masked token ${{ steps.google-token.outputs.token }}"
     
